# Generated by Django 5.2.7 on 2025-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginsession",
            name="last_login_email",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
