# Generated by Django 5.2.7 on 2025-11-14 16:40

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("tenant_name", models.CharField(max_length=100)),
                (
                    "server_name",
                    models.CharField(
                        help_text="VPS or server identifier", max_length=150
                    ),
                ),
                (
                    "desired_domain",
                    models.CharField(
                        blank=True,
                        help_text="Tenant's desired subdomain (e.g., 'store1', 'bigco').",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Standard", "Standard"),
                            ("Premium", "Premium"),
                        ],
                        default="Basic",
                        max_length=50,
                    ),
                ),
                ("subscription_start", models.DateField(auto_now_add=True)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Suspended", "Suspended")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("storage_used_mb", models.FloatField(default=0.0)),
                ("product_count", models.IntegerField(default=0)),
                ("order_count", models.IntegerField(default=0)),
                ("visitor_count_7d", models.IntegerField(default=0)),
                ("visitor_count_30d", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "total_orders_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("UPI", "UPI"),
                            ("CARD", "Credit/Debit Card"),
                        ],
                        default="COD",
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                        default="Unpaid",
                        max_length=30,
                    ),
                ),
                (
                    "payment_plan",
                    models.CharField(
                        choices=[("Weekly", "Weekly"), ("Monthly", "Monthly")],
                        default="Weekly",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenantRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=100)),
                ("desired_domain", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Standard", "Standard"),
                            ("Premium", "Premium"),
                        ],
                        default="Basic",
                        max_length=50,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("COD", "Cash On Delivery"),
                            ("UPI", "UPI"),
                            ("CARD", "Credit/Debit Card"),
                        ],
                        default="COD",
                        max_length=10,
                    ),
                ),
                (
                    "payment_plan",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                        default="Monthly",
                        max_length=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("requested_on", models.DateField(default=django.utils.timezone.now)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="customers.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
